apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pudim
  name: pudimmmmmmm
spec:
  containers:
  - image: msfidelis/pudim:v0
    name: pudim
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
